// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.gov.nsw.records.digitalarchive.helper.web;

import au.gov.nsw.records.digitalarchive.helper.model.WorkflowDesign;
import au.gov.nsw.records.digitalarchive.helper.web.ApplicationConversionServiceFactoryBean;
import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.core.convert.converter.Converter;
import org.springframework.format.FormatterRegistry;

privileged aspect ApplicationConversionServiceFactoryBean_Roo_ConversionService {
    
    declare @type: ApplicationConversionServiceFactoryBean: @Configurable;
    
    public Converter<WorkflowDesign, String> ApplicationConversionServiceFactoryBean.getWorkflowDesignToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<au.gov.nsw.records.digitalarchive.helper.model.WorkflowDesign, java.lang.String>() {
            public String convert(WorkflowDesign workflowDesign) {
                return new StringBuilder().append(workflowDesign.getName()).append(" ").append(workflowDesign.getXml()).append(" ").append(workflowDesign.getOwner()).toString();
            }
        };
    }
    
    public Converter<Long, WorkflowDesign> ApplicationConversionServiceFactoryBean.getIdToWorkflowDesignConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, au.gov.nsw.records.digitalarchive.helper.model.WorkflowDesign>() {
            public au.gov.nsw.records.digitalarchive.helper.model.WorkflowDesign convert(java.lang.Long id) {
                return WorkflowDesign.findWorkflowDesign(id);
            }
        };
    }
    
    public Converter<String, WorkflowDesign> ApplicationConversionServiceFactoryBean.getStringToWorkflowDesignConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, au.gov.nsw.records.digitalarchive.helper.model.WorkflowDesign>() {
            public au.gov.nsw.records.digitalarchive.helper.model.WorkflowDesign convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), WorkflowDesign.class);
            }
        };
    }
    
    public void ApplicationConversionServiceFactoryBean.installLabelConverters(FormatterRegistry registry) {
        registry.addConverter(getWorkflowDesignToStringConverter());
        registry.addConverter(getIdToWorkflowDesignConverter());
        registry.addConverter(getStringToWorkflowDesignConverter());
    }
    
    public void ApplicationConversionServiceFactoryBean.afterPropertiesSet() {
        super.afterPropertiesSet();
        installLabelConverters(getObject());
    }
    
}
