// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.gov.nsw.records.digitalarchive.helper.web;

import au.gov.nsw.records.digitalarchive.helper.model.WorkflowDesign;
import au.gov.nsw.records.digitalarchive.helper.web.WorkflowDesignController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect WorkflowDesignController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String WorkflowDesignController.create(@Valid WorkflowDesign workflowDesign, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, workflowDesign);
            return "workflowdesigns/create";
        }
        uiModel.asMap().clear();
        workflowDesign.persist();
        return "redirect:/workflowdesigns/" + encodeUrlPathSegment(workflowDesign.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String WorkflowDesignController.createForm(Model uiModel) {
        populateEditForm(uiModel, new WorkflowDesign());
        return "workflowdesigns/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String WorkflowDesignController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("workflowdesign", WorkflowDesign.findWorkflowDesign(id));
        uiModel.addAttribute("itemId", id);
        return "workflowdesigns/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String WorkflowDesignController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("workflowdesigns", WorkflowDesign.findWorkflowDesignEntries(firstResult, sizeNo));
            float nrOfPages = (float) WorkflowDesign.countWorkflowDesigns() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("workflowdesigns", WorkflowDesign.findAllWorkflowDesigns());
        }
        return "workflowdesigns/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String WorkflowDesignController.update(@Valid WorkflowDesign workflowDesign, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, workflowDesign);
            return "workflowdesigns/update";
        }
        uiModel.asMap().clear();
        workflowDesign.merge();
        return "redirect:/workflowdesigns/" + encodeUrlPathSegment(workflowDesign.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String WorkflowDesignController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, WorkflowDesign.findWorkflowDesign(id));
        return "workflowdesigns/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String WorkflowDesignController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        WorkflowDesign workflowDesign = WorkflowDesign.findWorkflowDesign(id);
        workflowDesign.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/workflowdesigns";
    }
    
    void WorkflowDesignController.populateEditForm(Model uiModel, WorkflowDesign workflowDesign) {
        uiModel.addAttribute("workflowDesign", workflowDesign);
    }
    
    String WorkflowDesignController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
