// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.gov.nsw.records.digitalarchive.helper.model;

import au.gov.nsw.records.digitalarchive.helper.model.WorkflowDesign;

privileged aspect WorkflowDesign_Roo_JavaBean {
    
    public String WorkflowDesign.getName() {
        return this.name;
    }
    
    public void WorkflowDesign.setName(String name) {
        this.name = name;
    }
    
    public String WorkflowDesign.getXml() {
        return this.xml;
    }
    
    public void WorkflowDesign.setXml(String xml) {
        this.xml = xml;
    }
    
    public String WorkflowDesign.getOwner() {
        return this.owner;
    }
    
    public void WorkflowDesign.setOwner(String owner) {
        this.owner = owner;
    }
    
}
