// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.gov.nsw.records.digitalarchive.helper.model;

import au.gov.nsw.records.digitalarchive.helper.model.WorkflowDesign;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect WorkflowDesign_Roo_Jpa_Entity {
    
    declare @type: WorkflowDesign: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long WorkflowDesign.id;
    
    @Version
    @Column(name = "version")
    private Integer WorkflowDesign.version;
    
    public Long WorkflowDesign.getId() {
        return this.id;
    }
    
    public void WorkflowDesign.setId(Long id) {
        this.id = id;
    }
    
    public Integer WorkflowDesign.getVersion() {
        return this.version;
    }
    
    public void WorkflowDesign.setVersion(Integer version) {
        this.version = version;
    }
    
}
