// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.gov.nsw.records.digitalarchive.helper.model;

import au.gov.nsw.records.digitalarchive.helper.model.WorkflowDesign;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect WorkflowDesign_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager WorkflowDesign.entityManager;
    
    public static final EntityManager WorkflowDesign.entityManager() {
        EntityManager em = new WorkflowDesign().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long WorkflowDesign.countWorkflowDesigns() {
        return entityManager().createQuery("SELECT COUNT(o) FROM WorkflowDesign o", Long.class).getSingleResult();
    }
    
    public static List<WorkflowDesign> WorkflowDesign.findAllWorkflowDesigns() {
        return entityManager().createQuery("SELECT o FROM WorkflowDesign o", WorkflowDesign.class).getResultList();
    }
    
    public static WorkflowDesign WorkflowDesign.findWorkflowDesign(Long id) {
        if (id == null) return null;
        return entityManager().find(WorkflowDesign.class, id);
    }
    
    public static List<WorkflowDesign> WorkflowDesign.findWorkflowDesignEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM WorkflowDesign o", WorkflowDesign.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void WorkflowDesign.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void WorkflowDesign.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            WorkflowDesign attached = WorkflowDesign.findWorkflowDesign(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void WorkflowDesign.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void WorkflowDesign.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public WorkflowDesign WorkflowDesign.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        WorkflowDesign merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
